import type { Metadata, Viewport } from "next";

import "./globals.css";


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Techdicto",
  description: "Generated by create next app",
};

export const viewport: Viewport ={
  maximumScale : 1.0,
  userScalable: false
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-dmsans antialiased  bg-[#08090A]`}
      >
        {children}
      </body>
    </html>
  );
}


